/* eslint-disable */
// Generated by @cloudflare/worker-config
import type { InferEnv, InferDurableNamespaces, InferMainModule } from "@cloudflare/worker-config";
import type Config from "./worker.config";

declare global {
	namespace Cloudflare {
		interface GlobalProps {
			mainModule: InferMainModule<typeof Config>;
			durableNamespaces: InferDurableNamespaces<typeof Config>;
		}
		interface Env extends InferEnv<typeof Config> {}
	}
	interface Env extends Cloudflare.Env {}
}
