import type { Config } from "./schema";

interface GenerateTypesOptions {
	/** The resolved config object */
	config: Config;
	/** Path to the config file (relative to project root) */
	configPath: string;
}

/**
 * Generate the content for worker-configuration.d.ts
 *
 * This generates a TypeScript declaration file that uses type inference
 * from the config file rather than fully-expanded types.
 *
 * @example
 * ```typescript
 * import { generateTypes } from "@cloudflare/worker-config";
 * import { writeFileSync } from "node:fs";
 *
 * const config = { name: "my-worker", entrypoint: "./src/index.ts", env: { ... } };
 *
 * const content = generateTypes({
 *   config,
 *   configPath: "./worker.config.ts",
 * });
 *
 * writeFileSync("worker-configuration.d.ts", content);
 * ```
 */
export function generateTypes(options: GenerateTypesOptions): string {
	const { config, configPath } = options;

	// Strip .ts/.js extension for import path
	const configImportPath = configPath.replace(/\.(ts|js|mts|mjs)$/, "");

	const lines = [
		"/* eslint-disable */",
		"// Generated by @cloudflare/worker-config",
	];

	// Import types based on what's needed
	if (config.entrypoint) {
		lines.push(
			`import type { InferEnv, InferDurableNamespaces } from "@cloudflare/worker-config";`
		);
	} else {
		lines.push(`import type { InferEnv } from "@cloudflare/worker-config";`);
	}

	lines.push(`import type Config from "${configImportPath}";`);

	// Import entrypoint module if it exists
	if (config.entrypoint) {
		const entrypointImportPath = config.entrypoint.replace(
			/\.(ts|js|mts|mjs)$/,
			""
		);
		lines.push(`import type * as MainModule from "${entrypointImportPath}";`);
	}

	lines.push("");
	lines.push("declare global {");
	lines.push("\tnamespace Cloudflare {");

	// GlobalProps (only if entrypoint exists)
	if (config.entrypoint) {
		lines.push("\t\tinterface GlobalProps {");
		lines.push("\t\t\tmainModule: typeof MainModule;");
		lines.push(
			"\t\t\tdurableNamespaces: InferDurableNamespaces<typeof Config>;"
		);
		lines.push("\t\t}");
	}

	// Env
	lines.push("\t\tinterface Env extends InferEnv<typeof Config> {}");

	lines.push("\t}");
	lines.push("\tinterface Env extends Cloudflare.Env {}");
	lines.push("}");
	lines.push(""); // trailing newline

	return lines.join("\n");
}
