import type * as MainModule from "./src/index";
import type Config from "./worker.config";
/* eslint-disable */
// Generated by @cloudflare/worker-config
import type {
	InferEnv,
	InferDurableNamespaces,
} from "@cloudflare/worker-config";

declare global {
	namespace Cloudflare {
		interface GlobalProps {
			mainModule: typeof MainModule;
			durableNamespaces: InferDurableNamespaces<typeof Config>;
		}
		interface Env extends InferEnv<typeof Config> {}
	}
	interface Env extends Cloudflare.Env {}
}
